### ISSUE TITLE
Crear endpoint para obtener obligaciones fiscales

### ISSUE THREAD

**Issue by damianfanaro** [igrowker/i003-youcreate-back#3]
Desarrollar el endpoint GET /api/obligaciones-fiscales que devuelva un resumen de las obligaciones fiscales del usuario según su país de residencia. Los datos deben incluir montos y fechas de vencimiento de los impuestos. Asegurarse de que los datos sean correctos y estén actualizados.

**Comment by Victorfernandolopez** [comment]
consulta: si bien la consigna es realisar el enpoint para visualizar los datos de los impuestos como, 1-el impuesto, 2- el  monto y 3- la fecha de vencimiento, estos impuestos son suministrados por el backend de forma automatica, o es el mismo usuario quien va registrando sus impuestos y la app solo le muestra lo que tiene que pagar y cuando se le vence?
